### ISSUE TITLE
Dont't focus on search input when come back from addon page.

### ISSUE THREAD

**Issue by milo** [nette/web-addons.nette.org#120]
Example:
You came on a addons main page (cursor is focused to search, that's fine).
But you don't search and you are rolling down.
You click on addon.
But you don't like them, so you press Backspace.
And now, you are on the top of page, because, cursor focus.

True story, happend with FF 17.0.1

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
