### ISSUE TITLE
Github Releases

### ISSUE THREAD

**Issue by vojtech-dobes** [nette/web-addons.nette.org#128]
I think making the maintaining of addon as easy as possible is good way to keep the addons updated. We could provide an option "Use Github releases". That would make the *older versions* link to lead to Github releases page. When the author of addon uses it, there is no need to show users much less detail page of our own (without changelog for example).

I would like to hear your opinion :).

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
