### ISSUE TITLE
Do not expire session when editing content / Autosave

### ISSUE THREAD

**Issue by smasty** [nette/web-addons.nette.org#136]
When editing the description of an addon, my session expired (it took some time to rewrite it) and when I clicked the Save button, I was redirected to the login screen. After logging in, the description was not changed and I had to rewrite it again. (Thankfully, going back in the browser had the textarea content saved)

I propose two solutions:

1) Extend the session expiration time when editing content
2) Implement autosave functionality to the edit form.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
