### ISSUE TITLE
Broken layout in Opera & IE

### ISSUE THREAD

**Issue by MartinMajor** [nette/web-addons.nette.org#142]
Some addons (eg. [Nextras\Datagrid](http://nette.merxes.cz/addons/nextras/datagrid) and [Twitter](http://nette.merxes.cz/addons/sodae/netrium-addons-twitter)) has broken layout in old Opera (ver. 12) and IE. It is caused by rendering scroll bar of #main element which causes that #sidebar element hasn't enought space for rendering next to #content element.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
