### ISSUE TITLE
Markdown - broken type of included code

### ISSUE THREAD

**Issue by brabijan** [nette/web-addons.nette.org#149]
Try insert into description for example this code - https://github.com/brabijan/images/blob/master/readme.md . In addon page you can see escaped `<pre>` and `<code>` tags.

here is the screenshot:
![images nette framework - addons plugins and components](https://cloud.githubusercontent.com/assets/2448709/2696779/a70139e8-c3e6-11e3-94ba-9898690c0cfd.png)

**Comment by sakren** [comment]
same here http://addons.nette.org/carrooi/nette-menu

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
