### ISSUE TITLE
Not able to update info about FileDownloader

### ISSUE THREAD

**Issue by jkuchar** [nette/web-addons.nette.org#157]
URL: http://addons.nette.org/manage.addon/edit?addonId=80

(updated only header)

![image](https://cloud.githubusercontent.com/assets/133822/3000591/b77b95a4-dd25-11e3-92a9-69b73b91e401.png)

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
