### ISSUE TITLE
Authors aren't updated from composer.json?

### ISSUE THREAD

**Issue by jkuchar** [nette/web-addons.nette.org#161]
I've updated [MFU](http://addons.nette.org/jkuchar/multiplefileupload) to version 1.1.0. However authors wasn't updated https://github.com/jkuchar/MultipleFileUpload/blob/master/composer.json#L6, what I'm doing wrong? Thanks!

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
