### ISSUE TITLE
Publish addon - form disappears after entering incorrect repo URL

### ISSUE THREAD

**Issue by Majkl578** [nette/web-addons.nette.org#162]
After JS error with the following message: "Sorry, we currently support only packagist."
![publish your addon nette framework - addons plugins and components](https://cloud.githubusercontent.com/assets/144181/3712305/67ab5d66-150b-11e4-979e-c4e785fcb912.png)

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
