### ISSUE TITLE
Parsedown

### ISSUE THREAD

**Issue by Vrtak-CZ** [nette/web-addons.nette.org#164]
http://parsedown.org/

**Comment by Vrtak-CZ** [comment]
or https://github.com/thephpleague/commonmark/

**Comment by dobesvac** [comment]
You mean to replace Markdown to Parsedown? I can look at it.

**Comment by dobesvac** [comment]
Finally, I have implemented both. CommonMark and Parsedown. Here is a link to the repository: https://github.com/dobesvac/nette-addons. I don't know why, but CommonMark does not parse html tables.

**Comment by dobesvac** [comment]
I almost forgot. I had to slightly modify the database. I changed the enumeration of the field descriptionFormat to 'tex', 'markdown', 'commonmark', 'parsedown' in the table addons.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
