### ISSUE TITLE
Forum avatars

### ISSUE THREAD

**Issue by vojtech-dobes** [nette/web-addons.nette.org#165]
If I understand how authentication works, it always updates user's data with information from forum. Could it also return information whether user has avatar on forum? If this information would known, it should be possible to create URL of avatar on addon's detail page. I suspect the field might be `use_avatar`, but I am afraid I am unable to verify that experimentally :).

/cc @Vrtak-CZ @dg

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
