### ISSUE TITLE
Componette

### ISSUE THREAD

**Issue by Vrtak-CZ** [nette/web-addons.nette.org#174]
What if we switch this project to https://github.com/componette/componette.com ? I mean move https://github.com/componette/componette.com to this repo.

@dg should add @f3l1x & @chemix push access to this repo and @milo should add @f3l1x access to Nette VPS?

**Comment by f3l1x** [comment]
I think it's not a right plan. 

Followed by this: https://forum.nette.org/cs/23849-nette-addons-redesign-2-0#p167261

And I have my own VPS, I would like to keep it on it for at least 1 year.

**Comment by chemix** [comment]
We can minimalize "official Nette F." code. Componette is separated project, but with support from Nette F. I hope, we will soon switch addons.nette.org to componette.com (with 100% backward links solution) and propagate new addons portal with name Componette. I think, this code ("old" addons portal) is fine for beginner to study it. Like a new code of componette.org. My idea is, on componette.org create simple page "about" where we recapitulace all history (from first hackathon to last vrtaks commits and lot of ideas to simplification version from felix, and more) with link to study resources. 

So, plan for Q1/2016 is switch from previous addons portal to new, without links breaks outs. On felix VPS, and another repository. Where Felix is like master maintener with all right he needs to push project forward. 

(sorry I wrote en like cs ;-)

**Comment by Vrtak-CZ** [comment]
Redirects done
