### ISSUE TITLE
Consider respecting (invalid) "dist" info in composer.json 

### ISSUE THREAD

**Issue by JanTvrdik** [nette/web-addons.nette.org#30]
According to the specification it is invalid to have "dist field" (a field which allow you to specify url of custom distribution archive)  in composer.json. However Packagist does currently respect this field (so you can have a package on Packagist with a distribution archive different from what GitHub automatically generates).

Our current implementation ignores composer.json with invalid schema and because specifying "dist field" makes the schema invalid, it is now not possible to have an imported version with custom distribution archive.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
