### ISSUE TITLE
Intelligent authors handling with merging

### ISSUE THREAD

**Issue by JanTvrdik** [nette/web-addons.nette.org#41]
Currently we have two source of information about authors:

1. The user who adds the addon
2. Authors listed in composer.json

If (2) is empty, we generate it based on (1).

The issue with (2) is that we don't have theirs ids, so we can not create link to their profiles. However, we may have their e-mails which could be used to determine their id.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
