### ISSUE TITLE
Remove parameters from AddonManageFacade constructor

### ISSUE THREAD

**Issue by JanTvrdik** [nette/web-addons.nette.org#57]
Parameters passed to `AddonManageFacade` constructor are only used by method `addVersionFromValues()` and therefore should not be passed to constructor but only to the method which needs them.

This also allow us to remove method `createAddonManageFacade` from `ManagePresenter`.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
