### ISSUE TITLE
Turn voting into minireviews

### ISSUE THREAD

**Issue by NoxArt** [nette/web-addons.nette.org#68]
Hi,
similarly to people on StackOverflow I see a downvote without reason as a wasted opportunity (for everyone involved).

When an addon has 30% downvoted I don't know (as a potential user) if it's because people didn't like API or they think it has fewer features or because it's not documented properly or because it's buggy or untested or incompatible with something etc.
It's also bad for the author as he might get -1 without knowing what is it that he should ... and could ... improve.

A solution could be to connect voting with a comment, possibly split to pros/cons. Also I'd attach addon's version to such entry so the user can see if those issues faded away or if they're still present.

**Comment by Vrtak-CZ** [comment]
We are closing this project. Because there is https://github.com/componette/componette.com
